FROM maven:3.8.6-jdk-11-slim as builder

COPY . /build/mars-core
WORKDIR /build/mars-core

RUN mvn clean compile

FROM builder

USER mars

COPY --from=builder /build/mars-core /app/mars-core
WORKDIR /app/mars-core

VOLUME /logs/mars-core
VOLUME /shared

CMD ["mvn", "spring-boot:run"]