spring:
  sleuth:
    enabled: false


mars:
  witel: roc
  cookie:
    name: MARSID
    domain: localhost
    path: /
    http-only: true
    secure: false
  i18n:
    with-defaults: ${INCLUDE_DEFAULT_MESSAGES:true}
    externals: ${MESSAGES_FILES:}
