version: "3.8"
services:
  postgres:
    container_name: mars-postgres
    image: postgres:14.5
    restart: unless-stopped
    ports:
      - "15413:5432"
    env_file:
      - .env
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data