version: "3.8"
services:
  postgres:
    container_name: mars-postgres
    image: postgres:15.4
    ports:
      - "15413:5432"
    env_file:
      - .env
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    container_name: mars-redis
    image: redis:7.0.6
    ports:
      - "15379:6379"
    env_file:
      - .env
    volumes:
      - ./data/redis:/data