server:
  port: ${MARS_DISCOVERY_PORT:10919}

spring:
  application:
    name: mars-discovery
  profiles:
    include: directory
  sleuth:
    enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${MARS_DISCOVERY_URL:http://localhost:${server.port}}/eureka/