spring:
  redis:
    client-type: jedis
    client-name: "mars-roc"
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}


mars:
  witel: roc
  cookie:
    name: MARSID
    domain: localhost
    path: /
    http-only: true
    secure: false
  i18n:
    with-defaults: ${INCLUDE_DEFAULT_MESSAGES:true}
    externals: ${MESSAGES_FILES:}
