server:
  port: ${MARS_GATEWAY_PORT:10920}

spring:
  application:
    name: mars-gateway
  profiles:
    include: directory
  sleuth:
    enabled: true
  cloud:
    gateway:
      enabled: true
      routes:
        - id: mars-admin
          uri: lb://mars-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin/(?<path>.*),/$\{path}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: ${MARS_DISCOVERY_URL:http://${MARS_DISCOVERY_HOST:localhost}:${MARS_DISCOVERY_PORT:8761}}/eureka
