server:
  port: ${MARS_CORE_PORT:10920}

spring:
  application:
    name: mars-core
  jpa:
    database: postgresql
    generate-ddl: true
  flyway:
    table: mars_schema_history
    default-schema: ${DS_SCHEMA:mars}
    create-schemas: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DS_HOST:127.0.0.1}:${DS_PORT:15433}/${DS_DATABASE:tr2db}
    username: ${DS_USERNAME:mars}
    password: ${DS_PASSWORD:12qwaszx}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: mars-core
      schema: ${DS_SCHEMA:mars}
  jackson:
    default-property-inclusion: NON_NULL
    locale: id_ID
  task:
    execution:
      pool:
        queue-capacity: ${ASYNC_MAX_QUEUE:1000}
        core-size: ${ASYNC_CORE_POOL_SIZE:5}
        max-size: ${ASYNC_MAX_POOL_SIZE:20}

mars:
  secret: ${JWT_SECRET:}
  cors:
    max-age: 3600
    allowed-origin-patterns: [ ]
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:10220}
    allowed-headers: "*"
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allow-credentials: on
    exposed-headers: [ ]
  telegram:
    token: ${TELEGRAM_BOT_TOKEN:709411539:AAHGXOA0nIOYtcpzIQegY7O0NO7Vzu1Uug0}
