server:
  port: ${MARS_WITEL_PORT:${random.int(10000,30000)}}

dump:
  ds:
    host: ${MARS_WITEL_DS_HOST:${DS_HOST:localhost}}
    port: ${MARS_WITEL_DS_PORT:${DS_PORT:5432}}
    url: ${MARS_WITEL_DS_URL:postgresql://${dump.ds.host}:${dump.ds.port}}/mars-witel?${MARS_WITEL_DS_QUERY:}
    username: ${MARS_WITEL_DS_USERNAME:${DS_USERNAME:postgres}}
    password: ${MARS_WITEL_DS_PASSWORD:${DS_PASSWORD:postgres}}
    schema: ${MARS_WITEL_DS_SCHEMA:${DS_SCHEMA:public}}

spring:
  profiles:
    include: common, directory
  application:
    name: mars-${mars.witel}
  redis:
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    client-type: jedis
    client-name: ${spring.application.name}
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:${dump.ds.url}
    username: ${dump.ds.username}
    password: ${dump.ds.password}
    hikari:
      pool-name: ${spring.application.name}
      schema: ${dump.ds.schema}
      maximum-pool-size: 10
  flyway:
    default-schema: ${dump.ds.schema}
    schemas: ${dump.ds.schema}
    create-schemas: true
    url: jdbc:${dump.ds.url}
    user: ${dump.ds.username}
    password: ${dump.ds.password}
  data:
    web:
      pageable:
        default-page-size: 20

eureka:
  instance:
    appname: ${spring.application.name}
    app-group-name: witel
    instance-id: ${spring.application.name}:${random.value}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${MARS_DISCOVERY_URL:http://${MARS_DISCOVERY_HOST:localhost}:${MARS_DISCOVERY_PORT:8761}}/eureka
    registry-fetch-interval-seconds: 10

keycloak:
  auth-server-url: https://auth.scaraz.dev
  realm: mars
  bearer-only: true
  confidential-port: 0
  resource: mars-witel-resource
  credentials:
    secret: IGQcuDoTsZYgx6ODfpuHLFXSBsFqDncO

mars:
  witel: ${MARS_WITEL}
  telegram:
    enabled: true
    name: mars-bot
    type: long_polling
    token: 5477841359:AAEsfQWb6sVmj0oTMTodgpjZyGuTw8PR2FI
    async:
      core-pool-size: 3
      max-pool-isze: 10
      queue-capacity: 100