server:
  port: ${MARS_DISCOVERY_PORT:10919}
  shutdown: graceful

spring:
  application:
    name: mars-discovery

eureka:
  instance:
    appname: ${spring.application.name}
    app-group-name: mars
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${MARS_DISCOVERY_HOST:localhost}:${server.port}/eureka/
