server:
  port: ${MARS_ADMIN_PORT:10921}

dump:
  ds:
    host: ${MARS_ADMIN_DS_HOST:${DS_HOST:localhost}}
    port: ${MARS_ADMIN_DS_PORT:${DS_PORT:5432}}
    url: ${MARS_ADMIN_DS_URL:postgresql://${dump.ds.host}:${dump.ds.port}}/mars-admin?${MARS_ADMIN_DS_QUERY:}
    username: ${MARS_ADMIN_DS_USERNAME:${DS_USERNAME:postgres}}
    password: ${MARS_ADMIN_DS_PASSWORD:${DS_PASSWORD:postgres}}
    schema: ${MARS_ADMIN_DS_SCHEMA:${DS_SCHEMA:public}}
  witel:
    ds:
      host: ${MARS_WITEL_DS_HOST:${DS_HOST:localhost}}
      port: ${MARS_WITEL_DS_PORT:${DS_PORT:5432}}
      url: ${MARS_WITEL_DS_URL:postgresql://${dump.ds.host}:${dump.ds.port}}/mars-witel?${MARS_WITEL_DS_QUERY:}
      username: ${MARS_WITEL_DS_USERNAME:${DS_USERNAME:postgres}}
      password: ${MARS_WITEL_DS_PASSWORD:${DS_PASSWORD:postgres}}
      schema: ${MARS_WITEL_DS_SCHEMA:${DS_SCHEMA:public}}

spring:
  application:
    name: mars-admin
  profiles:
    include: common, directory
  redis:
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    client-type: jedis
    client-name: mars-bot
  jpa:
    show-sql: false
    generate-ddl: false
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:${dump.ds.url}
    jdbc-url: jdbc:${dump.ds.url}
    username: ${dump.ds.username}
    password: ${dump.ds.password}
    hikari:
      pool-name: ${spring.application.name}
      schema: ${dump.ds.schema}
      maximum-pool-size: 10
      jdbc-url: jdbc:${dump.ds.url}
  flyway:
    default-schema: ${dump.ds.schema}
    schemas: ${dump.ds.schema}
    create-schemas: true
    url: jdbc:${dump.ds.url}
    user: ${dump.ds.username}
    password: ${dump.ds.password}

witel:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:${dump.witel.ds.url}
    jdbc-url: jdbc:${dump.witel.ds.url}
    username: ${dump.witel.ds.username}
    password: ${dump.witel.ds.password}
    hikari:
      pool-name: ${spring.application.name}
      schema: ${dump.witel.ds.schema}
      maximum-pool-size: 10
      jdbc-url: jdbc:${dump.witel.ds.url}

telegram:
  enabled: true
  name: mars-bot
  type: long_polling
  async:
    core-pool-size: 3
    max-pool-isze: 30
    queue-capacity: 100

#keycloak:
#  auth-server-url: ${KC_URL:https://auth.scaraz.dev}
#  realm: ${KC_REALM:mars}
#  bearer-only: true
#  confidential-port: 0
#  resource: ${KC_CLIENT_ID:mars-administration-resource}
#  credentials:
#    secret: ${CLIENT_SECRET:M4TY7sysFrwxNTJGwArpx6Vjwd5RFiIR}

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}::${random.value}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${MARS_DISCOVERY_URL:http://${MARS_DISCOVERY_HOST:localhost}:${MARS_DISCOVERY_PORT:8761}}/eureka

mars:
  witel: ROC
