keycloak:
  auth-server-url: https://auth.scaraz.dev
  realm: mars
  bearer-only: true
  confidential-port: 0
  resource: mars-admin-resource
  credentials:
    secret: IGQcuDoTsZYgx6ODfpuHLFXSBsFqDncO

telegram:
  enabled: true
  name: mars-bot
  type: long_polling
  token: 5477841359:AAEsfQWb6sVmj0oTMTodgpjZyGuTw8PR2FI
  async:
    core-pool-size: 3
    max-pool-isze: 10
    queue-capacity: 100