server:
  port: ${MARS_ADMIN_PORT:10921}
  shutdown: graceful

dump:
  keycloak:
    url: ${KC_URL:https://auth.scaraz.dev}
    realm: ${KC_REALM:mars}
    resource: ${KC_RESOURCE:mars-client-api}
  datasource:
    host: ${MARS_ADMIN_DS_HOST:localhost}
    port: ${MARS_ADMIN_DS_PORT:5432}
    url: ${dump.datasource.host}:${dump.datasource.port}
    username: ${MARS_ADMIN_DS_USERNAME:${DS_USERNAME:postgres}}
    password: ${MARS_ADMIN_DS_PASSWORD:${DS_PASSWORD:postgres}}
    schema: ${MARS_ADMIN_DS_SCHEMA:${DS_SCHEMA:public}}
    database: ${MARS_ADMIN_DS_DATABASE:mars-admin}

spring:
  profiles:
    include: common
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: mars-admin
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: false
    show-sql: ${DS_SHOW_SQL:false}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${MARS_ADMIN_DS_URL:jdbc:postgresql://${dump.datasource.url}/${dump.datasource.database}}
    username: ${dump.datasource.username}
    password: ${dump.datasource.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ${spring.application.name}
      schema: ${dump.datasource.schema}
      maximum-pool-size: ${DS_POOL_SIZE:10}
#  flyway:
#    create-schemas: true
#    default-schema: ${dump.datasource.schema}
  task:
    execution:
      pool:
        queue-capacity: ${ASYNC_MAX_QUEUE:1000}
        core-size: ${ASYNC_CORE_POOL_SIZE:5}
        max-size: ${ASYNC_MAX_POOL_SIZE:20}
      shutdown:
        await-termination: true
        await-termination-period: 30s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:${dump.keycloak.url}/realms/${dump.keycloak.realm}}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  bearer-only: true
  auth-server-url: ${dump.keycloak.url}
  realm: ${dump.keycloak.realm}
  resource: ${dump.keycloak.resource}

mars:
  witel: ${MARS_WITEL:roc}
  directory:
    tmp: ${MARS_TMP_DIRECTORY:D:/TMP/mars}
    shared: ${MARS_SHARED_DIRECTORY:D:/TMP/mars}
  keycloak-server:
    admin:
      username: admin
      password: admin
