server:
  port: ${MARS_CORE_PORT:10920}
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

spring:
  application:
    name: mars-roc
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  data:
    web:
      pageable:
        default-page-size: 50
    redis:
      client-type: jedis
      client-name: "mars-roc"
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
  jpa:
    database: postgresql
    generate-ddl: false
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
  flyway:
    table: mars_schema_history
    default-schema: ${DS_SCHEMA:mars}
    create-schemas: true
    locations: ${MIGRATION_DIR:classpath:db/migrations}
    out-of-order: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DS_HOST:127.0.0.1}:${DS_PORT:15433}/${DS_DATABASE:tr2db}
    username: ${DS_USERNAME:mars}
    password: ${DS_PASSWORD:12qwaszx}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: mars-core
      schema: ${DS_SCHEMA:mars}
  jackson:
    default-property-inclusion: NON_NULL
    locale: id_ID
  task:
    execution:
      pool:
        queue-capacity: ${ASYNC_MAX_QUEUE:1000}
        core-size: ${ASYNC_CORE_POOL_SIZE:5}
        max-size: ${ASYNC_MAX_POOL_SIZE:20}

logging:
  file:
    name: ${LOG_DIRECTORY:D:/webs/mars-java/logs}/${LOG_NAME:${spring.application.name}}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: ${LOG_ARCHIVE:${LOG_DIRECTORY:D:/webs/mars-java/logs}/archive}/${LOG_NAME:${spring.application.name}}-%d{yyyy-MM-dd}.%i.log
  group:
    spring: org.springframework,com.netflix,io.micrometer,feign,_org.springframework.web,io.undertow,org.xnio,Validator
    http: okhttp3,org.apache
    database: com.zaxxer.hikari,io.lettuce,io.netty,org.hibernate,org.postgresql,org.redisson
    java: sun.net,javax.management,javax.activation,unknown.jul.logger,sun.rmi,sun.rmi.transport,jdk.event,reactor,io.github.resilience4j,sun.awt,com.sun,org.jboss
    swagger: io.swagger,springfox,org.springdoc
    keycloak: org.keycloak
    flyway: org.flywaydb.core
    mars: dev.scaraz.mars.telegram,dev.scaraz.mars.common
  level:
    root: ${LOG_LEVEL:debug}
    spring: warn
    database: warn
    http: warn
    keycloak: warn
    java: off
    swagger: off
    flyway: warn
    mars: ${LOG_MARS_LIB_LEVEL:info}
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Jakarta}) %clr[${spring.application.name},%thread,%X{traceId:-},%X{spanId:-}] %highlight(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Jakarta} [${spring.application.name},%thread,%X{traceId:-},%X{spanId:-}] %-5p %logger{0} %m%n'
  charset:
    console: utf-8
    file: utf-8

mars:
  timestamp: @timestamp@
  secret: ${JWT_SECRET:}
  cors:
    max-age: 3600
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:10220}
    allowed-headers: "*"
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allow-credentials: on
    exposed-headers: Tc-Count, X-Total-Count, X-Sort, filename
  directory:
    tmp: ${MARS_TMP_DIRECTORY:D:/TMP/mars}
    shared: ${MARS_SHARED_DIRECTORY:D:/TMP/mars}

telegram:
  type: long_polling
  name: "mars-roc"
  token: ${TELEGRAM_BOT_TOKEN:709411539:AAHGXOA0nIOYtcpzIQegY7O0NO7Vzu1Uug0}
  async:
    core-pool-size: ${TELEGRAM_CORE_POOL:2}
    max-pool-size: ${TELEGRAM_MAX_POOL:30}
    queue-capacity: ${TELEGRAM_QUEUE_CAPACITY:1000}
