

keycloak:
  realm: "mars"
  auth-server-url: "https://auth.scaraz.dev/"
  ssl-required: "external"
  resource: "mars-api"
  verify-token-audience: true
  credentials:
    secret: "7NVox7xYucxG5RU9sEImZ2NqpYLgxmcg"
  confidential-port: 0