server:
  port: ${MARS_DISCOVERY_PORT:10920}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${MARS_DISCOVERY_URL:http://127.0.0.1:${server.port}}/eureka/

spring:
  application:
    name: mars-discovery
  sleuth:
    enabled: true

logging:
  file:
    name: ${LOG_DIRECTORY:D:/webs/mars-java/logs}/${LOG_NAME:${spring.application.name}}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: ${LOG_ARCHIVE:${LOG_DIRECTORY:D:/webs/mars-java/logs}/archive}/${LOG_NAME:${spring.application.name}}-%d{yyyy-MM-dd}.%i.log
  group:
    spring: org.springframework,com.netflix,io.micrometer,feign,_org.springframework.web,io.undertow,org.xnio,Validator
    http: okhttp3,org.apache
    database: com.zaxxer.hikari,io.lettuce,io.netty,org.hibernate,org.postgresql,org.redisson
    java: sun.net,javax.management,javax.activation,unknown.jul.logger,sun.rmi,sun.rmi.transport,jdk.event,reactor,io.github.resilience4j,sun.awt,com.sun,org.jboss
    swagger: io.swagger,springfox,org.springdoc
    keycloak: org.keycloak
    flyway: org.flywaydb.core
    mars: dev.scaraz.mars.telegram,dev.scaraz.mars.common
  level:
    root: ${LOG_LEVEL:debug}
    spring: warn
    database: warn
    http: warn
    keycloak: warn
    java: off
    swagger: off
    flyway: warn
    mars: ${LOG_MARS_LIB_LEVEL:info}
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Jakarta}) %clr[${spring.application.name},%thread,%X{traceId:-},%X{spanId:-}] %highlight(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Jakarta} [${spring.application.name},%thread,%X{traceId:-},%X{spanId:-}] %-5p %logger{0} %m%n'
  charset:
    console: utf-8
    file: utf-8